---
title: "Reporte con Crosstalk"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(plotly)
library(crosstalk)
library(dplyr)
source("R/00_librerias.R")
source("R/01_extraer.R")

# Generar datos de ejemplo
data <- df_transparencia %>% 
  mutate(periodo_recod = case_when(periodo == "3° Trimestre 2024 (Julio - Septiembre)" ~ "t1",
                                   periodo == "2° Trimestre 2024 (Abril - Junio)" ~ "t2")) %>% 
  select(periodo_recod, sujeto_obligado, it)


head(data)
# Convertir los datos a un objeto compartido (SharedData)
shared_data <- SharedData$new(data, ~sujeto_obligado)

# Crear gráfico interactivo con Crosstalk
grafico <- plot_ly(shared_data, x = ~periodo_recod, y = ~it, type = 'bar', mode = 'lines',
        color = ~periodo_recod) %>%
  layout(title = "Gráfico interactivo con selección de categoría")

# Agregar un filtro interactivo
filtro <- filter_select("categoria", "Selecciona una categoría", shared_data, ~sujeto_obligado)
```

Row
-------------------------------------

### Año 1

```{r}
page_fluid(
  
  navset_pill_list(
    nav_panel(title = "Año 2023",

  # Segunda fila: Tabla y barra lateral
  layout_column_wrap(
    width = 1,  # La tabla ocupa toda la fila
    card(
      card_header("Transparencia"),
      layout_sidebar(
        fillable = TRUE, 
        sidebar = sidebar(
          title = "Filtros",
          width = "25%",
          class = "fw-bold font-monospace",
          filtro
        ),
        grafico,  # Aquí va la tabla principal
        tagList(
          tags$button(class = "download-button",
                      tagList(fontawesome::fa("download"), "Descargar tabla como .CSV"),
                      onclick = "Reactable.downloadDataCSV('indice-tabla-1', 'indice-tabla-1.csv')")
        )
      )
    )
  )
  ),
  
  nav_panel(title = "Año 2024")
  
  )
  
)

```

### Año 2
