---
title: ""
output:
  html_document:
    theme: 
      version: 5
    css: "estilo/estilo_tablero.css"
    logo: estilo/img/logoAAIP.svg
---

```{r setup, include=FALSE}
library(here)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(scipen = 999)
```


```{r message=FALSE, warning=FALSE}
library(here)

# Librerías utilizadas
source(here("R/00_librerias.R"))

# Funciones necesarias
source(here("R/00_funciones.R"))

# Lectura de base de datos
source(here("R/01_extraer.R"))

# Limpieza y preparación de la base de datos
source(here("R/02_transformar.R"))

# Colores y estilo organizacional
source(here("estilo/99_manual_estilo.R"))

# Filtros
source(here("R/03_filtros.R"))

# Gráficos
#source(here("R/04_graficos.R"))

### Recursos del Tablero
source(here("R/modulos/mod_tarjeta_global.R"))
source(here("R/modulos/mod_tabla_general.R"))
source(here("R/modulos/mod_serie_tiempo.R"))
source(here("R/modulos/mod_tabla_x_dimension.R"))
source(here("R/modulos/mod_metodologia.R"))
```


```{r}
page_navbar(
  title = "Índice de Transparencia",
  #theme = theme,  # Aquí aplicamos `_brand.yml`,
  
  nav_panel(
    "Resultados",
    div(
      class = "container-fluid",
      
      navset_tab(
        nav_panel("Resultado global",
                  height = 450,
                  tarjeta_global
        ),
        
        nav_panel("Por sujeto obligado",
                  layout_column_wrap(
                    width = 1,
                    tarjeta_x_so
                  )
        ),
        
        nav_panel("Por dimensión",
                  layout_column_wrap(
                    width = 1,
                    tarjeta_x_dim
                  )
        ),
        
        nav_panel("Evolución en el tiempo",
                  layout_column_wrap(
                    width = 1,
                    tarjeta_serie_tiempo
                  )
        )
      )
    )
  ),
  
  nav_panel("Metodología",
            tarjeta_metodologia)
)

```

